[package]
name = "Regression"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty-machine = "0.5.4"
serde = "1"
serde_derive = "1"
rand = "0.6.5"
utils = { path = "../utils" }

[[bin]]
name = "linear_regression"
path = "src/main.rs"